global:
  scrape_interval: 5s # metric pulling every 5 second
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'spring-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # domain and port of prometheus